
plugin.prefix: "§l§bWORLD§r"

# COMMAND EASYWORLD
command.unknow: "{prefix} §7usage: §b/easyworld help"
command.nopermission: "{prefix} §7Você não tem permissão para usar este comando!"

# COMMAND EASYWORLD LIST
command.list.message: "{prefix} §7Lista de mundos e configurações:"

# COMMAND EASYWORLD MENU
command.menu.sucess: "{prefix} §7Definições de {world} foram atualizadas!"

# COMMAND EASYWORLD CREATE
world.create.has: "{prefix} §7O mundo {world} já existe!"
world.create.sucess: "{prefix} §7O mundo {world} foi criado com sucesso!!"
world.create.help: "{prefix} §7Usage: §b/easyworld create (name) (seed = random) (generator = normal)"

# COMMAND EASYWORLD DELETE
world.delete.non: "{prefix} §7O mundo {world} não existe!"
world.delete.sucess: "{prefix} §7O mundo {world} foi removido com sucesso!!"
world.delete.help: "{prefix} §7Usage: §b/easyworld delete (name)"

# COMMAND EASYWORLD RENAME
world.rename.non: "{prefix} §7O mundo {world} não existe!"
world.rename.has: "{prefix} §7O mundo {world} ja existe!"
world.rename.sucess: "{prefix} §7O nome do mundo {world} foi alterado para {new_name} com sucesso!!"
world.rename.help: "{prefix} §7Usage: §b/easyworld rename (OldName) (NewName)"

# COMMAND EASYWORLD TELEPORT
world.tp.help: "{prefix} §7Usage: §b/easyworld teleport (name)"
world.tp.unknow: "{prefix} §7O mundo {world} não existe!"
world.tp.sucess: "{prefix} §7Teleportado para {world} com sucesso!"

# EASYWORLD PROTECTED
world.protect.place.message: "{prefix} §7Você não tem permissão para botar blocos nesse mundo!"
world.protect.break.message: "{prefix} §7Você não tem permissão para quebrar blocos nesse mundo!" 

# EASYWORLD CHAT LOCKED
world.chat.locked.message: "{prefix} §7Você não tem permissão para mandar mensagens deste mundo!" 

# EASYWORLD COMBAT DISABLE
world.combat.off.message: "§cO combate está desativado nesse mundo!"

# EASYWORLD BLOCK COMMAND
command.block.has: "{prefix} §7Esse comando ja foi bloqueado no mundo§b{world}§7!"
command.block.sucess: "{prefix} §7Comando bloqueado no mundo §b{world}§7!" 
command.block.error: "{prefix} §7Você não pode usar §{command}§7 no mundo §b{world}§7!"
command.block.help: "{prefix} §7Use /easyworld command (command)"
